# Generated by Django 5.0.3 on 2025-11-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0005_stock_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ['id'], 'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма позиции'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма заказа'),
        ),
        migrations.AlterIndexTogether(
            name='orderitems',
            index_together={('order', 'product')},
        ),
    ]
