# Generated by Django 5.0.3 on 2025-11-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitems_options_alter_orderitems_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Сумма позиции'),
        ),
    ]
