# Generated by Django 5.0.3 on 2025-11-04 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_stock_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-priority', '-start_date'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='pricetype',
            options={'verbose_name': 'Тип цены', 'verbose_name_plural': 'Типы цен'},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='price',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия'),
        ),
        migrations.AddField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='price',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чем выше значение, тем приоритетнее цена при пересечении периодов.'),
        ),
        migrations.AddField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала действия'),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.pricetype', verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='ms_uuid',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип цены'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'price_type'], name='products_pr_product_d90b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_58e198_idx'),
        ),
    ]
