# Generated by Django 5.0.3 on 2025-11-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_price_options_alter_pricetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='code',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='ms_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
